baseURL = "https://www.elizastarr.com"
languageCode = "en-us"
title = "eliza starr"
theme = "sam"

[params]
footerText =""
homepage = "home"

[[params.mainMenu]]
    link = "/about"
    text = "who is eliza?"

[[params.mainMenu]]
    link = "/downloads/cv.pdf"
    text = "curriculum vitae"

[[params.mainMenu]]
    link = "/downloads/cv.pdf"
    text = "résumé"

